s = "Hello, World"
print(s.upper(), s.lower())
print(len(s))
print(s[0], s[-1], s[0:5], s[7:], s[:5], s[::-1], s[::2])
print("  pad  ".strip() + "|")
print("xxhixx".strip("x"))
print(s.replace("World", "Python"))
print(s.split(", "))
print("a b  c".split())
print("-".join(["a", "b", "c"]))
print(s.startswith("Hello"), s.endswith("!"))
print(s.find("World"), s.find("zzz"))
print(s.count("l"))
print("abc" * 3)
print("a" + "b" + "c")
print("Ali".isalpha(), "123".isdigit(), "".isdigit())
print("hello world".title(), "hELLO".capitalize())
print("A" < "B", "apple" < "banana")
print("ell" in s, "zzz" not in s)
