nums = [5, 3, 8, 1]
print(nums, len(nums))
nums.append(10)
print(nums)
nums.insert(0, 99)
print(nums)
print(nums.pop(), nums.pop(0))
print(nums)
nums.remove(3)
print(nums)
print(nums.index(8), nums.count(8))
nums.sort()
print(nums)
nums.sort(reverse=True)
print(nums)
nums.reverse()
print(nums)
print(sorted([3, 1, 2]), sorted(["b", "a"]), sorted([1,3,2], reverse=True))
print(sum([1, 2, 3]), min([4, 2, 9]), max([4, 2, 9]))
print(min(3, 1, 2), max(3, 1, 2))
print([1, 2] + [3], [0] * 3)
print(nums[1:3], nums[-2:])
copy = nums.copy()
copy.append(1000)
print(len(nums), len(copy))
print(list("abc"), list(range(3)))
print("a", "b", sep="-")
print("no newline", end="")
print("|")
print(1, 2, 3, sep="", end="!\n")
