print(bool(0), bool(1), bool(""), bool("a"))
print(bool([]), bool([0]), bool({}), bool({"a": 1}))
print(bool(None), bool(0.0))
print(not True, not 0, not "")
print(True and False, True or False)
print(1 and 2, 0 and 2, 0 or 3, 1 or 3)
print(None == None, None is None)
print([] == [], [1] == [1], [1] == [2])
print((1, 2) == (1, 2))
print({"a": 1} == {"a": 1})
print(1 == 1.0, 1 is 1)
print(1 < 2 < 3, 1 < 2 > 5)
print(3 != 4, "a" != "a")
